---

- name: Verify
  hosts: all
  vars:
    __galaxy_version: "{{ lookup('env', 'GALAXY_VERSION') }}"
  tasks:
    - name: Check version
      uri:
        url: http://localhost:8080/api/version
      register: response
      failed_when: response.status != 200 or (__galaxy_version != 'dev' and response.json.version_major != lookup('env', 'GALAXY_VERSION'))
      # this is just to wait until the server is up, we can stop retrying on any response
      until: response.status > 0
      retries: 60
      delay: 1
