---
language: python
python: "2.7"
sudo: required

before_install:
  - export GALAXY_HOME=/home/galaxy
  - export GALAXY_TRAVIS_USER=galaxy
  - export GALAXY_UID=1450
  - export GALAXY_GID=1450
  - sudo groupadd -r $GALAXY_TRAVIS_USER -g $GALAXY_GID
  - sudo useradd -u $GALAXY_UID -r -g $GALAXY_TRAVIS_USER -d $GALAXY_HOME -p travis_testing -c "Galaxy user" $GALAXY_TRAVIS_USER
  - sudo mkdir $GALAXY_HOME
  - sudo chown -R $GALAXY_TRAVIS_USER:$GALAXY_TRAVIS_USER $GALAXY_HOME
  - sudo chmod -R 755 $GALAXY_HOME

install:
  # Install an upgraded pip and virtualenv
  - sudo apt-get install git
  - sudo apt-get install python-pip
  - pip install virtualenv
  - pip install --upgrade pip

  # Install Ansible.
  - pip install ansible==2.4

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:
  - ansible-playbook -i "localhost, " -c local tests/test_playbook.yml
  - python -m unittest tests.test_seqtodict
