---
- name: Copy subdomain static files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/{{ object.value }}"
    mode: '0644'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
  with_fileglob: "{{ galaxy_themes_ansible_file_path }}/{{ subdomain.name }}/static/{{ object.value }}*"

- name: Copy files from dist
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/dist/"
    mode: '0644'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
  with_fileglob: "{{ galaxy_themes_ansible_file_path }}/{{ subdomain.name }}/static/dist/*"

- name: Copy files from dist
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/dist/"
    mode: '0644'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
  with_fileglob: "{{ galaxy_themes_ansible_file_path }}/{{ subdomain.name }}/static/dist/*"

- name: Copy custom welcome.html
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/welcome.html/index.html"
    mode: '0644'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
  with_fileglob: "{{ galaxy_themes_ansible_file_path }}/{{ subdomain.name }}/static/welcome.html"
  when: custom_welcome.stat.exists
