---
# Configure Gravity

- name: Gravity setup
  block:

    - name: Register Galaxy config with Gravity
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl register {{ galaxy_config_file }}"
      args:
        creates: "{{ galaxy_gravity_state_dir }}/configstate.yaml"

    - name: Update Gravity process management files
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl update"
      args:
        creates: "{{ galaxy_gravity_state_dir }}/supervisor/supervisord.conf.d"

  environment:
    GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  remote_user: "{{ galaxy_remote_users.galaxy | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(__galaxy_become_user) }}"
