---
# Instantiate managed config files

- name: Managed config setup
  block:

    - name: Ensure Galaxy version is set
      include_tasks: _inc_galaxy_version.yml
      when: __galaxy_major_version is undefined

    # force: no in the following 2 tasks will not overwrite existing configs
    - name: Instantiate managed configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: no
      with_items: "{{ galaxy_managed_config_files }}"

    - name: Instantiate managed configuration templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: no
      with_items: "{{ galaxy_managed_config_templates }}"

  remote_user: "{{ galaxy_remote_users.galaxy | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(__galaxy_become_user) }}"
