---

# Having pip installed on $PYTHONPATH can break upgrading it, so we install
# once with $PYTHONPATH set (in case it's needed for virtualenv) and then once
# the venv is created we upgrade pip with $PYTHONPATH unset

- name: Create Galaxy virtualenv
  pip:
    name: pip
    virtualenv: "{{ galaxy_venv_dir }}"
    extra_args: "{{ pip_extra_args | default(omit) }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ galaxy_virtualenv_python | default(omit) }}"
  environment:
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: Ensure pip is the desired release
  pip:
    name:
      - pip
    state: "{{ galaxy_pip_version | default('latest') }}"
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
